# Generated by Django 4.1.7 on 2023-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.TextField(unique=True),
        ),
    ]
