# Generated by Django 4.1.7 on 2023-03-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_position_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='core.position'),
        ),
    ]
