# Generated by Django 4.1.7 on 2023-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_url_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.CharField(default='location', max_length=50, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
