# Generated by Django 4.1.7 on 2023-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_position_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(default='location', max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
    ]
