# Generated by Django 4.1.7 on 2023-03-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_location_category_alter_location_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='position',
            new_name='location',
        ),
    ]
