# Generated by Django 4.1.7 on 2023-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_position_url_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='location_url',
            field=models.CharField(max_length=200, verbose_name='location url'),
        ),
    ]
