# Generated by Django 4.1.7 on 2023-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_url_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=30.3032, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=59.9594, verbose_name='longitude'),
        ),
    ]
